import greybox from '../../stages/greybox/stage.json' with { type: 'json' };

type Point = { x:number; y:number };
type Surface = { id:string; kind:'solid'|'one-way'; y:number; xMin:number; xMax:number };
type Ledge = { id:string; x:number; y:number; inward:-1|1 };
type Spawn = { id:string; x:number; y:number; facing:-1|1 };
type MovingPlatform = { id:string; kind:'solid'|'one-way'; width:number; path:Point[]; periodFrames:number; phaseFrames:number };
type Hazard = { id:string; kind:'damage'|'launch'|'ko'; x:number; y:number; radius:number; activeFrames:number; inactiveFrames:number; phaseFrames:number };
type StagePack = { id:string; identity:{displayName:string}; surfaces:Surface[]; ledges:Ledge[]; spawns:Spawn[]; blastZone:{left:number;right:number;bottom:number;top:number}; camera:{bounds:{left:number;right:number;bottom:number;top:number};padding:number;minZoom:number;maxZoom:number}; movingPlatforms:MovingPlatform[]; hazards:Hazard[]; [key:string]:unknown };
const canvas = document.querySelector<HTMLCanvasElement>('#view')!; const ctx = canvas.getContext('2d')!;
const textarea = document.querySelector<HTMLTextAreaElement>('#json')!; const status = document.querySelector<HTMLDivElement>('#status')!;
const frameInput = document.querySelector<HTMLInputElement>('#frame')!; const frameLabel = document.querySelector<HTMLDivElement>('#frameLabel')!;
textarea.value = JSON.stringify(greybox, null, 2);
let pack: StagePack = structuredClone(greybox) as StagePack; let frame = 0;
function validate(p:unknown): asserts p is StagePack { const q=p as Partial<StagePack>; if (!q?.id || !Array.isArray(q.surfaces) || !q.blastZone || !q.camera || !Array.isArray(q.spawns)) throw new Error('stage requires id, surfaces, spawns, blastZone and camera'); if (q.spawns.length < 2) throw new Error('stage requires at least two spawn points'); for (const s of q.surfaces) if (!(Number.isInteger(s.xMin)&&Number.isInteger(s.xMax)&&Number.isInteger(s.y)&&s.xMin<s.xMax)) throw new Error(`invalid surface ${s.id}`); }
function movingPoint(platform:MovingPlatform, f:number):Point { const path=platform.path; if(path.length===1) return path[0]!; const period=Math.max(2,platform.periodFrames|0); const half=Math.max(1,Math.trunc(period/2)); const local=((f+(platform.phaseFrames|0))%period+period)%period; const forward=local<=half; const t=(forward?local:period-local)/half; const segments=path.length-1; const scaled=Math.min(segments-1e-9,t*segments); const i=Math.floor(scaled); const q=scaled-i; const a=path[i]!, b=path[Math.min(i+1,path.length-1)]!; return {x:Math.round(a.x+(b.x-a)*q),y:Math.round(a.y+(b.y-a)*q)}; }
function bounds(p:StagePack){ const b=p.camera.bounds; return {left:b.left,right:b.right,bottom:b.bottom,top:b.top}; }
function sx(x:number,b:{left:number;right:number}){return (x-b.left)/(b.right-b.left)*canvas.width} function sy(y:number,b:{bottom:number;top:number}){return canvas.height-(y-b.bottom)/(b.top-b.bottom)*canvas.height}
function draw(){ const b=bounds(pack); ctx.clearRect(0,0,canvas.width,canvas.height); ctx.lineWidth=5; ctx.strokeStyle='#d8e6ff'; for(const s of pack.surfaces){ctx.beginPath();ctx.moveTo(sx(s.xMin,b),sy(s.y,b));ctx.lineTo(sx(s.xMax,b),sy(s.y,b));ctx.stroke()} ctx.fillStyle='#9fd3ff'; for(const l of pack.ledges){ctx.beginPath();ctx.arc(sx(l.x,b),sy(l.y,b),7,0,Math.PI*2);ctx.fill()} ctx.fillStyle='#fff0a6'; for(const s of pack.spawns){ctx.beginPath();ctx.arc(sx(s.x,b),sy(s.y,b),10,0,Math.PI*2);ctx.fill()} ctx.strokeStyle='#83ffbd'; for(const m of pack.movingPlatforms){const pt=movingPoint(m,frame);ctx.beginPath();ctx.moveTo(sx(pt.x-m.width/2,b),sy(pt.y,b));ctx.lineTo(sx(pt.x+m.width/2,b),sy(pt.y,b));ctx.stroke()} for(const h of pack.hazards){const cycle=h.activeFrames+h.inactiveFrames;const active=cycle>0&&((frame+h.phaseFrames)%cycle+cycle)%cycle<h.activeFrames;ctx.strokeStyle=active?'#ff9e9e':'#704848';ctx.beginPath();ctx.arc(sx(h.x,b),sy(h.y,b),Math.abs(sx(h.x+h.radius,b)-sx(h.x,b)),0,Math.PI*2);ctx.stroke()} frameLabel.textContent=`Frame ${frame}`; }
function apply(){try{const parsed:unknown=JSON.parse(textarea.value);validate(parsed);pack=parsed;status.textContent=`PASS — ${pack.id}: ${pack.surfaces.length} surfaces, ${pack.ledges.length} ledges, ${pack.spawns.length} spawns, ${pack.movingPlatforms.length} moving platforms, ${pack.hazards.length} hazards.`;draw()}catch(e){status.textContent=`FAIL — ${e instanceof Error?e.message:String(e)}`}}
document.querySelector('#apply')!.addEventListener('click',apply); document.querySelector('#copy')!.addEventListener('click',()=>navigator.clipboard.writeText(textarea.value)); frameInput.addEventListener('input',()=>{frame=Number(frameInput.value);draw()}); apply();
