import { fixed } from '../../deterministic-math/src/fixed.js';
import type { CompiledStageDefinition } from '../../content/src/compileStage.js';
import { applyStageHazards, withStageHazards } from '../../sim/src/stageHazards.js';
import { createTwoFighterMatch, type MatchInputFrame, type MatchStepResult } from '../../sim/src/match.js';
import type { WorldState } from '../../sim/src/types.js';
function assert(condition:unknown,message:string):asserts condition{if(!condition)throw new Error(`K37 stage-hazard certification failure: ${message}`)}
const stage:CompiledStageDefinition={id:'hazard-cert',displayName:'Hazard Cert',surfaces:[],walls:[],ledges:[],spawns:[],stockRules:{blastLeft:fixed.fromInt(-10),blastRight:fixed.fromInt(10),blastBottom:fixed.fromInt(-8),blastTop:fixed.fromInt(8),respawnXSpacing:fixed.fromInt(1),respawnY:fixed.fromInt(6),respawnFrames:60,respawnInvulnerableFrames:120},camera:{left:fixed.fromInt(-8),right:fixed.fromInt(8),bottom:fixed.fromInt(-6),top:fixed.fromInt(6),padding:fixed.fromInt(1),minZoom:fixed.fromInt(1),maxZoom:fixed.fromInt(2)},movingPlatforms:[],hazards:[{id:'lava',kind:'damage',x:fixed.zero,y:fixed.zero,radius:fixed.fromInt(2),activeFrames:10,inactiveFrames:10,phaseFrames:0},{id:'bumper',kind:'launch',x:fixed.fromInt(4),y:fixed.zero,radius:fixed.fromInt(1),activeFrames:20,inactiveFrames:0,phaseFrames:0},{id:'pit',kind:'ko',x:fixed.fromInt(-4),y:fixed.zero,radius:fixed.fromInt(1),activeFrames:20,inactiveFrames:0,phaseFrames:0}]};
const policy={damageTenthsByHazardId:{lava:125},launchByHazardId:{bumper:{x:fixed.fromInt(-3),y:fixed.fromInt(4),hitstunFrames:20}}};
let world=createTwoFighterMatch(37); world={...world,fighters:world.fighters.map((f,i)=>({...f,x:i===0?fixed.zero:fixed.fromInt(7),y:fixed.zero}))};
let applied=applyStageHazards(world,stage,policy); assert(applied.fighters[0]!.percentTenths===125,'active damage hazard must apply authored damage policy');
world={...world,fighters:world.fighters.map((f,i)=>({...f,x:i===0?fixed.fromInt(4):fixed.fromInt(7),y:fixed.zero}))}; applied=applyStageHazards(world,stage,policy); assert(applied.fighters[0]!.vx===fixed.fromInt(-3)&&applied.fighters[0]!.vy===fixed.fromInt(4)&&applied.fighters[0]!.hitstunFrames===20,'launch hazard must apply authored vector and hitstun');
world={...world,fighters:world.fighters.map((f,i)=>({...f,x:i===0?fixed.fromInt(-4):fixed.fromInt(7),y:fixed.zero}))}; applied=applyStageHazards(world,stage,policy); assert(applied.fighters[0]!.x<stage.stockRules.blastLeft&&applied.fighters[0]!.y<stage.stockRules.blastBottom,'KO hazard must place target beyond authored blast bounds for ordinary lifecycle resolution');
let captured:WorldState|null=null; const probe=(state:WorldState,_input:MatchInputFrame):MatchStepResult=>{captured=structuredClone(state);return{state:{...state,frame:state.frame+1},events:[]}}; const step=withStageHazards(probe,stage,policy); world={...createTwoFighterMatch(38),fighters:createTwoFighterMatch(38).fighters.map((f,i)=>({...f,x:i===0?fixed.zero:fixed.fromInt(7),y:fixed.zero}))}; step(world,{frame:world.frame,byFighterId:{}}); assert(captured!==null&&(captured as WorldState).fighters[0]!.percentTenths===125,'hazard adapter must feed modified authoritative state into ordinary match step');
console.log('K37 STAGE HAZARDS PASS — active stage geometry resolves parameterized damage/launch/KO effects into ordinary deterministic match composition without flagship values in the kernel.');
