import { fixed } from '../../deterministic-math/src/fixed.js';
import { applyGrabEscapeInput, withGrabEscape, type GrabEscapePolicy } from '../../sim/src/grabEscape.js';
import { createTwoFighterMatch, type MatchInputFrame, type MatchStepResult } from '../../sim/src/match.js';
import type { WorldState } from '../../sim/src/types.js';
function assert(condition:unknown,message:string):asserts condition{if(!condition)throw new Error(`K42 grab-escape certification failure: ${message}`)}
const policy:GrabEscapePolicy={enabled:true,escapeFrames:30,mashBonusFramesPerPress:6};
let world=createTwoFighterMatch(42); world={...world,fighters:world.fighters.map((fighter,index)=>index===0?{...fighter,grabTargetId:'fighter-b',grabFrames:10}: {...fighter,grabbedById:'fighter-a',grabFrames:10,locomotion:'grabbed'})};
const mash:MatchInputFrame={frame:world.frame,byFighterId:{'fighter-b':{frame:world.frame,moveX:0,moveY:0,jumpPressed:true,jumpHeld:true,attackPressed:true,specialPressed:true,grabPressed:false,dodgePressed:false,shieldHeld:false}}};
let prepared=applyGrabEscapeInput(world,mash,policy); assert(prepared.state.fighters[0]!.grabFrames===28&&prepared.state.fighters[1]!.grabFrames===28,'three mash presses must add authored progress to both sides of grab relationship');
world=prepared.state; prepared=applyGrabEscapeInput(world,{frame:world.frame,byFighterId:{'fighter-b':{frame:world.frame,moveX:0,moveY:0,jumpPressed:false,jumpHeld:false,attackPressed:true,dodgePressed:false,shieldHeld:false}}},policy); assert(prepared.events[0]?.type==='grab-escape'&&prepared.state.fighters.every((fighter)=>fighter.grabTargetId===null&&fighter.grabbedById===null),'threshold-crossing mash must release symmetric grab relationship and emit semantic escape event');
let captured:WorldState|null=null; const probe=(state:WorldState,_input:MatchInputFrame):MatchStepResult=>{captured=structuredClone(state);return{state:{...state,frame:state.frame+1},events:[]}};
world=createTwoFighterMatch(43); world={...world,fighters:world.fighters.map((fighter,index)=>index===0?{...fighter,grabTargetId:'fighter-b',grabFrames:25}: {...fighter,grabbedById:'fighter-a',grabFrames:25,locomotion:'grabbed'})}; const wrapped=withGrabEscape(probe,policy); const result=wrapped(world,{frame:world.frame,byFighterId:{'fighter-b':{frame:world.frame,moveX:0,moveY:0,jumpPressed:false,jumpHeld:false,attackPressed:true,dodgePressed:false,shieldHeld:false}}}); assert(captured!==null&&(captured as WorldState).fighters[0]!.grabTargetId===null&&result.events[0]?.type==='grab-escape','grab escape must occur before ordinary match maintenance and remain observable');
world={...world,fighters:world.fighters.map((fighter,index)=>index===0?{...fighter,grabAction:{actionId:'greybox:forward-throw',frame:1}}:fighter)}; prepared=applyGrabEscapeInput(world,mash,policy); assert(prepared.events.length===0&&prepared.state.fighters[0]!.grabTargetId==='fighter-b','active authored pummel/throw timeline must not be mash-escaped under base policy');
console.log('K42 GRAB ESCAPE PASS — mash inputs advance existing rollback grabFrames, release relationships symmetrically before match maintenance, emit semantic events, and cannot interrupt active authored grab actions.');
