import { compileFighterFollowUps } from '../../content/src/compileFollowUps.js';
import { applyMoveFollowUps, withMoveFollowUps } from '../../sim/src/moveFollowUps.js';
import { createTwoFighterMatch, type MatchInputFrame, type MatchStepResult } from '../../sim/src/match.js';
import type { WorldState } from '../../sim/src/types.js';
function assert(condition:unknown,message:string):asserts condition{if(!condition)throw new Error(`K43 follow-up certification failure: ${message}`)}
const pack={id:'combo-cert',moves:{jab:{totalFrames:12,timeline:[],followUps:[{input:'attack' as const,startFrame:6,endFrame:10,nextMove:'jab-2',requireContact:false}]},'jab-2':{totalFrames:14,timeline:[],followUps:[{input:'attack' as const,startFrame:7,endFrame:11,nextMove:'jab-3',requireContact:true}]},'jab-3':{totalFrames:18,timeline:[]},rapid:{totalFrames:6,timeline:[],followUps:[{input:'attack' as const,startFrame:3,endFrame:5,nextMove:'rapid',requireContact:false}]}}};
const followUps=compileFighterFollowUps(pack); assert(followUps.get('combo-cert:jab')?.[0]?.nextMoveId==='combo-cert:jab-2','compiler must scope follow-up target to fighter definition');
let world=createTwoFighterMatch(43); world={...world,fighters:world.fighters.map((fighter,index)=>index===0?{...fighter,definitionId:'combo-cert',attack:{attackId:'combo-cert:jab',frame:7,hitTargets:[]}}:fighter)};
const attackInput=(frame:number):MatchInputFrame=>({frame,byFighterId:{'fighter-a':{frame,moveX:0,moveY:0,jumpPressed:false,jumpHeld:false,attackPressed:true,dodgePressed:false,shieldHeld:false}}});
world=applyMoveFollowUps(world,attackInput(world.frame),followUps); assert(world.fighters[0]!.attack?.attackId==='combo-cert:jab-2'&&world.fighters[0]!.attack?.frame===0,'eligible attack press must transition to next authored move at frame zero');
world={...world,fighters:world.fighters.map((fighter,index)=>index===0?{...fighter,attack:{attackId:'combo-cert:jab-2',frame:8,hitTargets:[]}}:fighter)}; const blocked=applyMoveFollowUps(world,attackInput(world.frame),followUps); assert(blocked.fighters[0]!.attack?.attackId==='combo-cert:jab-2','contact-required follow-up must not transition without hit confirmation');
world={...world,fighters:world.fighters.map((fighter,index)=>index===0?{...fighter,attack:{attackId:'combo-cert:jab-2',frame:8,hitTargets:['fighter-b']}}:fighter)}; const chained=applyMoveFollowUps(world,attackInput(world.frame),followUps); assert(chained.fighters[0]!.attack?.attackId==='combo-cert:jab-3','contact-required follow-up must transition after existing hitTargets confirm contact');
world={...world,fighters:world.fighters.map((fighter,index)=>index===0?{...fighter,attack:{attackId:'combo-cert:rapid',frame:4,hitTargets:[]}}:fighter)}; const looped=applyMoveFollowUps(world,attackInput(world.frame),followUps); assert(looped.fighters[0]!.attack?.attackId==='combo-cert:rapid'&&looped.fighters[0]!.attack?.frame===0,'self follow-up must support repeated-press rapid-jab style loops');
let captured:WorldState|null=null;const probe=(state:WorldState,_input:MatchInputFrame):MatchStepResult=>{captured=structuredClone(state);return{state:{...state,frame:state.frame+1},events:[]}};world={...world,fighters:world.fighters.map((fighter,index)=>index===0?{...fighter,attack:{attackId:'combo-cert:jab',frame:7,hitTargets:[]}}:fighter)};withMoveFollowUps(probe,followUps)(world,attackInput(world.frame));assert(captured!==null&&(captured as WorldState).fighters[0]!.attack?.attackId==='combo-cert:jab-2','follow-up wrapper must transition before ordinary match step');
console.log('K43 FOLLOW-UP PASS — jab chains and repeated-press rapid sequences are fighter-authored move transitions with frame/contact gates and no character-specific simulation code.');
