import type { FighterState, ItemState, LocomotionState, MatchRuntimeState, OwnedEntityState, SimInputFrame, StageLedge, StageSurface, WorldState } from './types.js';

export const WORLD_BINARY_VERSION = 17;
const locomotionCode: Record<LocomotionState, number> = { idle:0,walk:1,dash:2,run:3,turn:4,crouch:5,'jump-squat':6,airborne:7,landing:8,'ledge-hang':9,'air-dodge':10,'spot-dodge':11,roll:12,'tech-in-place':13,'tech-roll':14,knockdown:15,grabbed:16,respawn:17 };
class ByteWriter { private readonly bytes:number[]=[]; private readonly encoder=new TextEncoder(); u8(v:number){this.bytes.push(v&255)} u16(v:number){const x=v&65535;this.u8(x);this.u8(x>>>8)} i16(v:number){this.u16(v&65535)} u32(v:number){const x=v>>>0;this.u8(x);this.u8(x>>>8);this.u8(x>>>16);this.u8(x>>>24)} i32(v:number){this.u32(v>>>0)} i64(v:number){if(!Number.isSafeInteger(v))throw new Error(`binary state requires safe integer, got ${v}`);const x=BigInt.asUintN(64,BigInt(v));for(let s=0n;s<64n;s+=8n)this.u8(Number((x>>s)&255n))} bool(v:boolean){this.u8(v?1:0)} string(v:string){const e=this.encoder.encode(v);if(e.length>65535)throw new Error('binary state string exceeds 65535 bytes');this.u16(e.length);for(const b of e)this.u8(b)} finish(){return Uint8Array.from(this.bytes)} }
function writeInput(w:ByteWriter,i:SimInputFrame){w.i32(i.frame);w.i16(i.moveX);w.i16(i.moveY);w.bool(i.jumpPressed);w.bool(i.jumpHeld);w.bool(Boolean(i.attackPressed));w.bool(Boolean(i.specialPressed));w.bool(Boolean(i.grabPressed));w.i16(i.smashX??0);w.i16(i.smashY??0);w.bool(i.dodgePressed);w.bool(i.shieldHeld)}
function writeSurface(w:ByteWriter,s:StageSurface){w.string(s.id);w.u8(s.kind==='solid'?0:1);w.i64(s.y);w.i64(s.xMin);w.i64(s.xMax)} function writeLedge(w:ByteWriter,l:StageLedge){w.string(l.id);w.i64(l.x);w.i64(l.y);w.i16(l.inward)} function writeOptionalString(w:ByteWriter,v:string|null){w.bool(v!==null);if(v!==null)w.string(v)}
function writeFighter(w:ByteWriter,f:FighterState){
  w.string(f.id);w.string(f.definitionId);w.i64(f.x);w.i64(f.y);w.i64(f.vx);w.i64(f.vy);w.bool(f.grounded);w.bool(f.groundSurfaceId!==null);if(f.groundSurfaceId!==null)w.string(f.groundSurfaceId);w.i16(f.facing);w.u8(locomotionCode[f.locomotion]);w.u32(f.locomotionFrame);w.u8(f.jumpsRemaining);w.bool(f.fastFalling);w.u16(f.dropThroughFrames);w.u16(f.jumpBufferFrames);writeOptionalString(w,f.ledgeId);w.u16(f.ledgeRegrabLockoutFrames);w.u16(f.invulnerableFrames);w.u16(f.dodgeCooldownFrames);w.u16(f.techBufferFrames);w.u16(f.landingLagFrames);w.u32(f.percentTenths);w.u16(f.hitlagFrames);w.u16(f.hitstunFrames);
  w.bool(f.attack!==null);if(f.attack){w.string(f.attack.attackId);w.u16(f.attack.frame);w.u16(f.attack.chargeFrames??0);const t=[...f.attack.hitTargets].sort();w.u16(t.length);for(const id of t)w.string(id)}
  const charge=f.smashCharge??null;w.bool(charge!==null);if(charge){w.string(charge.attackId);w.u16(charge.frames);w.u8(charge.axis==='x'?0:1);w.i16(charge.direction)}
  const recent=f.recentAttackIds??[];if(recent.length>255)throw new Error('recent attack history exceeds binary format capacity');w.u8(recent.length);for(const attackId of recent)w.string(attackId);
  w.bool(f.shielding);w.u16(f.shieldHealth);w.u16(f.shieldStunFrames);w.u16(f.shieldRegenDelayFrames);writeOptionalString(w,f.grabTargetId);writeOptionalString(w,f.grabbedById);w.u16(f.grabFrames);w.bool(f.grabAction!==null);if(f.grabAction){w.string(f.grabAction.actionId);w.u16(f.grabAction.frame)}writeOptionalString(w,f.lastHitById);w.i32(f.lastHitFrame);w.u8(f.stocks);w.bool(f.eliminated);w.u16(f.respawnFrames);if(f.inputHistory.length>65535)throw new Error('input history exceeds binary format capacity');w.u16(f.inputHistory.length);for(const i of f.inputHistory)writeInput(w,i)
}
function writeEntity(w:ByteWriter,e:OwnedEntityState){w.string(e.id);w.string(e.definitionId);w.string(e.ownerId);w.string(e.ownerDefinitionId);w.i64(e.x);w.i64(e.y);w.i64(e.vx);w.i64(e.vy);w.i16(e.facing);w.u16(e.ageFrames);w.u16(e.lifetimeFrames);w.u8(e.hitsRemaining);const t=[...e.hitTargets].sort();w.u16(t.length);for(const id of t)w.string(id)}
function writeItem(w:ByteWriter,i:ItemState){w.string(i.id);w.string(i.definitionId);w.i64(i.x);w.i64(i.y);w.i64(i.vx);w.i64(i.vy);writeOptionalString(w,i.holderId);w.u16(i.usesRemaining);w.u32(i.ageFrames)}
function writeMatch(w:ByteWriter,m:MatchRuntimeState|undefined){w.bool(m!==undefined);if(!m)return;w.u8(m.mode==='stock'?0:m.mode==='time'?1:2);w.bool(m.framesRemaining!==null);if(m.framesRemaining!==null)w.u32(m.framesRemaining);const scores=Object.entries(m.scores).sort(([a],[b])=>a.localeCompare(b));w.u16(scores.length);for(const[id,score]of scores){w.string(id);w.i32(score)}writeOptionalString(w,m.winningTeamId);w.bool(m.suddenDeath);w.bool(m.ended)}
export function serializeWorldState(state:WorldState):Uint8Array{const w=new ByteWriter();w.u8(0x53);w.u8(0x4c);w.u8(0x50);w.u8(0x46);w.u16(WORLD_BINARY_VERSION);w.u32(state.frame);w.u32(state.seed);writeOptionalString(w,state.winnerId);writeMatch(w,state.match);w.u32(state.nextEntitySerial??1);w.u32(state.nextItemSerial??1);const surfaces=[...state.surfaces].sort((a,b)=>a.id.localeCompare(b.id));w.u16(surfaces.length);for(const s of surfaces)writeSurface(w,s);const ledges=[...state.ledges].sort((a,b)=>a.id.localeCompare(b.id));w.u16(ledges.length);for(const l of ledges)writeLedge(w,l);const fighters=[...state.fighters].sort((a,b)=>a.id.localeCompare(b.id));w.u16(fighters.length);for(const f of fighters)writeFighter(w,f);const entities=[...(state.entities??[])].sort((a,b)=>a.id.localeCompare(b.id));w.u16(entities.length);for(const e of entities)writeEntity(w,e);const items=[...(state.items??[])].sort((a,b)=>a.id.localeCompare(b.id));w.u16(items.length);for(const i of items)writeItem(w,i);return w.finish()}
