#!/usr/bin/env node
import { access, mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const fightersRoot = join(root, 'fighters');
const generatedPath = join(root, 'packages', 'content', 'src', 'generated', 'entityRegistry.ts');
const command = process.argv[2] ?? 'check';
const ID = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const FIXED_MIN = 10_000;
const FIXED_MAX = 100_000_000;
const fail = (message) => { throw new Error(message); };
const assert = (value, message) => { if (!value) fail(message); };
const object = (value) => value !== null && typeof value === 'object' && !Array.isArray(value);
const json = async (path) => JSON.parse(await readFile(path, 'utf8'));

function fixed(value, label, { allowZero = true, positive = false } = {}) {
  assert(Number.isInteger(value), `${label} must be integer fixed-point data`);
  if (positive) assert(value > 0, `${label} must be positive`);
  const magnitude = Math.abs(value);
  assert((allowZero && magnitude === 0) || (magnitude >= FIXED_MIN && magnitude <= FIXED_MAX), `${label}=${value} looks mis-scaled; fixed geometry uses 1,000,000 units per world unit`);
}

function validateEntity(entity, label) {
  assert(object(entity), `${label} must be object`);
  assert(['projectile','trap','summon','weapon'].includes(entity.kind), `${label}.kind invalid`);
  assert(Number.isInteger(entity.lifetimeFrames) && entity.lifetimeFrames >= 1 && entity.lifetimeFrames <= 65535, `${label}.lifetimeFrames invalid`);
  fixed(entity.radius, `${label}.radius`, { allowZero: false, positive: true });
  for (const key of ['spawnOffsetX','spawnOffsetY','velocityX','velocityY']) fixed(entity[key], `${label}.${key}`);
  fixed(entity.gravity, `${label}.gravity`);
  for (const key of ['damageTenths','hitlagFrames','hitstunFrames']) assert(Number.isInteger(entity[key]) && entity[key] >= 0, `${label}.${key} invalid`);
  for (const key of ['baseKnockback','growthPer100Percent']) fixed(entity[key], `${label}.${key}`);
  assert(Number.isInteger(entity.directionX) && Number.isInteger(entity.directionY) && (entity.directionX !== 0 || entity.directionY !== 0), `${label} launch direction cannot be zero vector`);
  assert(typeof entity.destroyOnHit === 'boolean', `${label}.destroyOnHit must be boolean`);
  assert(Number.isInteger(entity.maxHits) && entity.maxHits >= 1 && entity.maxHits <= 255, `${label}.maxHits invalid`);
}

async function loadAll() {
  const dirs = (await readdir(fightersRoot, { withFileTypes: true })).filter((entry) => entry.isDirectory() && !entry.name.startsWith('.')).map((entry) => entry.name).sort();
  const packs = [];
  for (const fighterId of dirs) {
    const path = join(fightersRoot, fighterId, 'entities.json');
    try { await access(path); } catch { continue; }
    const pack = await json(path);
    assert(pack.schemaVersion === 1, `${fighterId}: entities schemaVersion must be 1`);
    assert(pack.fighterId === fighterId && ID.test(pack.fighterId), `${fighterId}: entities fighterId must match folder`);
    assert(object(pack.entities), `${fighterId}: entities object missing`);
    for (const [entityId, entity] of Object.entries(pack.entities).sort(([a],[b]) => a.localeCompare(b))) {
      assert(ID.test(entityId), `${fighterId}: invalid entity id ${entityId}`);
      validateEntity(entity, `${fighterId}:${entityId}`);
    }
    packs.push(pack);
  }
  return packs;
}

async function check() {
  const packs = await loadAll();
  const count = packs.reduce((sum, pack) => sum + Object.keys(pack.entities).length, 0);
  for (const pack of packs) console.log(`${pack.fighterId}: entities ${Object.keys(pack.entities).length}`);
  console.log(`Entity pack validation PASS (${packs.length} fighters, ${count} entities).`);
}

async function build() {
  const packs = await loadAll();
  await mkdir(dirname(generatedPath), { recursive: true });
  const text = `/* Generated by scripts/entity-packs.mjs. Do not edit. */\nexport const FIGHTER_ENTITY_PACKS = ${JSON.stringify(packs, null, 2)} as const;\n`;
  await writeFile(generatedPath, text);
  console.log(`Generated entity registry for ${packs.length} fighter packs.`);
}

if (command === 'check') await check();
else if (command === 'build') await build();
else fail('Commands: check | build');
