#!/usr/bin/env node
import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root=resolve(dirname(fileURLToPath(import.meta.url)),'..'); const stagesRoot=join(root,'stages'); const generatedPath=join(root,'packages','content','src','generated','stageRegistry.ts'); const command=process.argv[2]??'check'; const ID=/^[a-z0-9]+(?:-[a-z0-9]+)*$/; const FIXED_MIN=10_000,FIXED_MAX=200_000_000;
const fail=(m)=>{throw new Error(m)}; const assert=(v,m)=>{if(!v)fail(m)}; const object=(v)=>v!==null&&typeof v==='object'&&!Array.isArray(v); const json=async(path)=>JSON.parse(await readFile(path,'utf8'));
function fixed(value,label,{positive=false,zero=true}={}){assert(Number.isInteger(value),`${label} must be deterministic integer/fixed-point data`);if(positive)assert(value>0,`${label} must be positive`);const mag=Math.abs(value);assert((zero&&mag===0)||(mag>=FIXED_MIN&&mag<=FIXED_MAX),`${label}=${value} looks mis-scaled; geometry uses 1,000,000 fixed units per world unit`)}
function uniqueIds(items,label){const ids=new Set();for(const item of items){assert(object(item)&&typeof item.id==='string'&&item.id.length>0,`${label} entry requires id`);assert(!ids.has(item.id),`${label} duplicates id ${item.id}`);ids.add(item.id)}}
function rect(value,label){assert(object(value),`${label} missing`);for(const key of ['left','right','bottom','top'])fixed(value[key],`${label}.${key}`);assert(value.left<value.right,`${label}.left must be < right`);assert(value.bottom<value.top,`${label}.bottom must be < top`)}
function validateStage(stage,folder){
 assert(object(stage),`${folder}: stage.json must be object`);assert(stage.schemaVersion===1,`${folder}: schemaVersion must be 1`);assert(stage.id===folder&&ID.test(stage.id),`${folder}: stage id must match folder`);assert(['draft','playable','certified','release'].includes(stage.status),`${folder}: invalid status`);assert(object(stage.identity)&&stage.identity.displayName,`${folder}: identity.displayName missing`);
 assert(Array.isArray(stage.surfaces)&&stage.surfaces.length>0,`${folder}: surfaces required`);uniqueIds(stage.surfaces,`${folder}: surfaces`);for(const s of stage.surfaces){assert(['solid','one-way'].includes(s.kind),`${folder}: surface ${s.id} invalid kind`);fixed(s.y,`${folder}: ${s.id}.y`);fixed(s.xMin,`${folder}: ${s.id}.xMin`);fixed(s.xMax,`${folder}: ${s.id}.xMax`);assert(s.xMin<s.xMax,`${folder}: ${s.id} xMin must be < xMax`)}
 const walls=stage.walls??[];assert(Array.isArray(walls),`${folder}: walls must be array`);uniqueIds(walls,`${folder}: walls`);for(const w of walls){fixed(w.x,`${folder}: wall ${w.id}.x`);fixed(w.yMin,`${folder}: wall ${w.id}.yMin`);fixed(w.yMax,`${folder}: wall ${w.id}.yMax`);assert(w.yMin<w.yMax,`${folder}: wall ${w.id} yMin must be < yMax`);assert(w.normal===-1||w.normal===1,`${folder}: wall ${w.id}.normal must be -1 or 1`)}
 assert(Array.isArray(stage.ledges),`${folder}: ledges must be array`);uniqueIds(stage.ledges,`${folder}: ledges`);for(const l of stage.ledges){fixed(l.x,`${folder}: ledge ${l.id}.x`);fixed(l.y,`${folder}: ledge ${l.id}.y`);assert(l.inward===-1||l.inward===1,`${folder}: ledge ${l.id}.inward must be -1 or 1`)}
 assert(Array.isArray(stage.spawns)&&stage.spawns.length>=2,`${folder}: at least 2 spawns required`);uniqueIds(stage.spawns,`${folder}: spawns`);for(const s of stage.spawns){fixed(s.x,`${folder}: spawn ${s.id}.x`);fixed(s.y,`${folder}: spawn ${s.id}.y`);assert(s.facing===-1||s.facing===1,`${folder}: spawn ${s.id}.facing must be -1 or 1`)}if(stage.status!=='draft')assert(stage.spawns.length>=4,`${folder}: publishable stage requires at least 4 player spawns`);
 rect(stage.blastZone,`${folder}: blastZone`);assert(object(stage.camera),`${folder}: camera missing`);rect(stage.camera.bounds,`${folder}: camera.bounds`);fixed(stage.camera.padding,`${folder}: camera.padding`,{positive:true,zero:false});fixed(stage.camera.minZoom,`${folder}: camera.minZoom`,{positive:true,zero:false});fixed(stage.camera.maxZoom,`${folder}: camera.maxZoom`,{positive:true,zero:false});assert(stage.camera.minZoom<=stage.camera.maxZoom,`${folder}: camera minZoom must be <= maxZoom`);assert(stage.blastZone.left<stage.camera.bounds.left&&stage.blastZone.right>stage.camera.bounds.right,`${folder}: horizontal blast zone must contain camera bounds`);assert(stage.blastZone.bottom<stage.camera.bounds.bottom&&stage.blastZone.top>stage.camera.bounds.top,`${folder}: vertical blast zone must contain camera bounds`);
 assert(Array.isArray(stage.movingPlatforms),`${folder}: movingPlatforms must be array`);uniqueIds(stage.movingPlatforms,`${folder}: movingPlatforms`);for(const p of stage.movingPlatforms){assert(['solid','one-way'].includes(p.kind),`${folder}: moving platform ${p.id} invalid kind`);fixed(p.width,`${folder}: moving platform ${p.id}.width`,{positive:true,zero:false});assert(Array.isArray(p.path)&&p.path.length>=2,`${folder}: moving platform ${p.id} requires 2+ path points`);for(const [i,point] of p.path.entries()){fixed(point.x,`${folder}: moving platform ${p.id}.path[${i}].x`);fixed(point.y,`${folder}: moving platform ${p.id}.path[${i}].y`)}assert(Number.isInteger(p.periodFrames)&&p.periodFrames>=2,`${folder}: moving platform ${p.id}.periodFrames invalid`);assert(Number.isInteger(p.phaseFrames)&&p.phaseFrames>=0,`${folder}: moving platform ${p.id}.phaseFrames invalid`)}
 assert(Array.isArray(stage.hazards),`${folder}: hazards must be array`);uniqueIds(stage.hazards,`${folder}: hazards`);for(const h of stage.hazards){assert(['damage','launch','ko'].includes(h.kind),`${folder}: hazard ${h.id} invalid kind`);fixed(h.x,`${folder}: hazard ${h.id}.x`);fixed(h.y,`${folder}: hazard ${h.id}.y`);fixed(h.radius,`${folder}: hazard ${h.id}.radius`,{positive:true,zero:false});for(const key of ['activeFrames','inactiveFrames','phaseFrames'])assert(Number.isInteger(h[key])&&h[key]>=(key==='activeFrames'?1:0),`${folder}: hazard ${h.id}.${key} invalid`)}
 assert(object(stage.provenance)&&Array.isArray(stage.provenance.assets),`${folder}: provenance missing`);
}
async function loadAll(){await mkdir(stagesRoot,{recursive:true});const dirs=(await readdir(stagesRoot,{withFileTypes:true})).filter((e)=>e.isDirectory()&&!e.name.startsWith('.')).map((e)=>e.name).sort();const stages=[];for(const id of dirs){const stage=await json(join(stagesRoot,id,'stage.json'));validateStage(stage,id);stages.push(stage)}return stages}
async function check(){const stages=await loadAll();for(const s of stages)console.log(`${s.id}: ${s.status} | surfaces ${s.surfaces.length} | walls ${(s.walls??[]).length} | ledges ${s.ledges.length} | spawns ${s.spawns.length} | moving ${s.movingPlatforms.length} | hazards ${s.hazards.length}`);console.log(`Stage pack validation PASS (${stages.length} stages).`)}
async function build(){const stages=await loadAll();await mkdir(dirname(generatedPath),{recursive:true});const normalized=stages.map((s)=>({...s,walls:s.walls??[]}));const active=normalized.filter((s)=>s.status!=='draft');const source=`/* Generated by scripts/stage-packs.mjs. Do not edit. */\nexport const ALL_STAGE_PACKS = ${JSON.stringify(normalized,null,2)} as const;\nexport const STAGE_IDS = ${JSON.stringify(active.map((s)=>s.id),null,2)} as const;\nexport const STAGE_PACKS = ${JSON.stringify(active,null,2)} as const;\n`;await writeFile(generatedPath,source);console.log(`Generated stage registry: ${active.length}/${normalized.length} publishable; ${normalized.length} total available to labs/tooling.`)}
if(command==='check')await check();else if(command==='build')await build();else fail('Commands: check | build');
