import {RollbackSession} from '../../../../packages/sim/src/rollback.js';
import {REPLAY_VERSION} from '../content/version.js';
import {OnlineRollbackPeer} from '../../../../packages/netcode/src/peer.js';
import {hashWorldState} from '../../../../packages/sim/src/stateHash.js';
import type {NetPacket} from '../../../../packages/netcode/src/protocol.js';
import type {SimInputFrame} from '../../../../packages/sim/src/types.js';
import {createDuel,stepDuel,type DuelOptions} from '../game/duel.js';
import {IDS} from '../game/session.js';
interface PairCode {version:3;session:string;options:DuelOptions;delay:number;sdp:RTCSessionDescriptionInit;}
/** Manual signaling keeps the match peer-to-peer; simulation and correction use PF rollback. */
export class OnlineDuel {
 readonly connection=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});private channel:RTCDataChannel|null=null;private peer:OnlineRollbackPeer|null=null;private session:string=crypto.randomUUID();private options:DuelOptions;private delay:number;private slot=0;ready=false;remoteFrame=0;rollbacks=0;status='Waiting for pairing';onReady:(options:DuelOptions)=>void=()=>{};onStatus:(status:string)=>void=()=>{};
 constructor(options:DuelOptions,delay=2){this.options={...options,cpu:[0,0]};this.delay=delay;this.connection.ondatachannel=e=>this.bind(e.channel);this.connection.onconnectionstatechange=()=>{if(['failed','disconnected','closed'].includes(this.connection.connectionState)){this.ready=false;this.report(`Connection ${this.connection.connectionState}`);}};}
 private report(s:string){this.status=s;this.onStatus(s);}
 private bind(channel:RTCDataChannel){this.channel=channel;channel.onopen=()=>{const initial=createDuel(this.options);const rollback=new RollbackSession(initial,stepDuel,{participants:IDS,historyFrames:240});this.peer=new OnlineRollbackPeer(rollback,{sessionId:this.session,peerId:`peer-${this.slot}`,participantIds:IDS,localParticipantIds:[IDS[this.slot]!],inputDelayFrames:this.delay,gameVersion:REPLAY_VERSION,contentHash:hashWorldState(initial)});this.send(this.peer.hello);this.report('Validating duel rules…');};channel.onmessage=e=>{try{if(typeof e.data!=='string'||e.data.length>64000)throw Error('Invalid packet size');const packet=JSON.parse(e.data) as NetPacket;if(!this.peer)throw Error('Peer is not initialized');this.peer.receive(packet);if(packet.type==='hello'&&!this.ready){this.ready=true;this.report('Connected · rollback active');this.onReady(this.options);}if(packet.type==='input')this.remoteFrame=Math.max(this.remoteFrame,packet.input.frame);}catch(error){this.ready=false;this.report(`Network error: ${String(error)}`);}};}
 private send(value:NetPacket){if(this.channel?.readyState==='open')this.channel.send(JSON.stringify(value));}
 private async code(){if(this.connection.iceGatheringState!=='complete')await new Promise<void>(resolve=>{const done=()=>{if(this.connection.iceGatheringState==='complete'){clearTimeout(timeout);this.connection.removeEventListener('icegatheringstatechange',done);resolve();}};const timeout=setTimeout(()=>{this.connection.removeEventListener('icegatheringstatechange',done);resolve();},5000);this.connection.addEventListener('icegatheringstatechange',done);});if(!this.connection.localDescription?.sdp.includes('a=candidate:'))throw Error('This browser exposed no WebRTC connection candidates. Try a network/browser that allows peer connections.');const data:PairCode={version:3,session:this.session,options:this.options,delay:this.delay,sdp:this.connection.localDescription!.toJSON()};return btoa(JSON.stringify(data));}
 private parse(code:string):PairCode{if(code.length>30000)throw Error('Pairing code is too long');const data=JSON.parse(atob(code.trim())) as PairCode;if(data.version!==3||!data.sdp?.sdp||!['offer','answer'].includes(data.sdp.type))throw Error('Invalid pairing code');if(!Number.isInteger(data.delay)||data.delay<0||data.delay>8)throw Error('Invalid input delay');return data;}
 async host(){this.slot=0;this.bind(this.connection.createDataChannel('spectris',{ordered:true}));await this.connection.setLocalDescription(await this.connection.createOffer());this.report('Send the invitation to your opponent');return this.code();}
 async join(code:string){const data=this.parse(code);if(data.sdp.type!=='offer')throw Error('An invitation is required');this.slot=1;this.options={...data.options,cpu:[0,0]};this.session=data.session;this.delay=data.delay;await this.connection.setRemoteDescription(data.sdp);await this.connection.setLocalDescription(await this.connection.createAnswer());this.report('Send the answer back to the host');return this.code();}
 async accept(code:string){const data=this.parse(code);if(data.sdp.type!=='answer'||data.session!==this.session)throw Error('Answer belongs to another duel');await this.connection.setRemoteDescription(data.sdp);this.report('Connecting…');}
 advance(input:SimInputFrame){if(!this.ready||!this.peer)return null;if(this.peer.currentFrame-this.remoteFrame>12){this.report('Waiting for opponent…');return null;}this.peer.submitLocalInput(IDS[this.slot]!,{...input,frame:this.peer.currentFrame});const result=this.peer.advance();result.outbound.forEach(p=>this.send(p));this.rollbacks+=result.resimulatedFrames;if(result.desyncs.length){this.ready=false;this.report(`Desync at frame ${result.desyncs[0]!.frame}; match stopped`);}return result;}
 close(){this.ready=false;this.channel?.close();this.connection.close();}
}
