import './style.css';
import { fixed as f } from '../../../packages/deterministic-math/src/fixed.js';
import { hashWorldState } from '../../../packages/sim/src/stateHash.js';
import { ReplayRecorder, ReplayPlayer, type ReplayTape } from '../../../packages/sim/src/replay.js';
import type { WorldState,SimInputFrame } from '../../../packages/sim/src/types.js';
import { createSession,stepSession,gameData,neutral,IDS } from './game/session.js';
import { Renderer } from './presentation/renderer.js';
import { SpectrisShell } from './platform/shell.js';
import { downloadJson } from './platform/storage.js';
import { MOVES,ATTACKS,compileMoves } from './content/knight/moves/index.js';
const app=document.querySelector<HTMLDivElement>('#app')!,shell=new SpectrisShell();
let renderer:Renderer;
try{renderer=new Renderer(document.querySelector('#canvas')!);}catch(error){app.innerHTML='<div class="error"><h1>WebGL 2 is required</h1><p>Enable hardware acceleration and reload to enter the Sanctum.</p></div>';throw error;}
let world=createSession(),previous=world,menu=true,paused=false,local=false,debug=false,dev=false,showHelp=false,accumulator=0,lastTime=performance.now(),introUntil=0,toastUntil=0;
let dummy='still',tape:ReplayTape|null=null,playback:ReplayPlayer|null=null,playbackFrames=new Map<number,ReplayTape['frames'][number]>(),slots:(ReplayTape|null)[]=Array.from({length:5},()=>null),slot=0,recorder:ReplayRecorder;
let simMs=0,steps=0,lastInput:SimInputFrame=neutral(0),fps=60,frameTimes:number[]=[];
function record(){recorder=new ReplayRecorder(world,{gameVersion:'spectris-feel-v1',participantIds:IDS,stageId:'mirror-sanctum',rulesetId:'feel-lab'},120);}
record();
const $=<T extends HTMLElement=HTMLElement>(s:string)=>app.querySelector<T>(s)!;
function on(s:string,fn:()=>void){app.querySelector(s)?.addEventListener('click',fn);}
function toast(text:string){let el=app.querySelector('.toast');if(!el){el=document.createElement('div');el.className='toast';app.append(el);}el.textContent=text;toastUntil=performance.now()+3000;}
function start(two=false){local=two;menu=false;paused=false;frozen=false;showHelp=false;playback=null;shell.input.clear();world=createSession();previous=world;record();shell.begin(two);introUntil=performance.now()+2200;accumulator=0;renderUi();}
function title(){menu=true;paused=false;dev=false;playback=null;shell.openTitle();shell.input.clear();renderUi();}
function controls(){return `<div class="modal-shade"><section class="modal"><button class="close" id="close-help" aria-label="Close controls">×</button><div class="eyebrow">The first exchange</div><h2>One blade. Two ways to fight.</h2><p>Wings extend your aerial reach. Cape trades speed for weight. Switch in the air once; landing, catching a ledge, or being hit refreshes the switch.</p><table class="controls"><thead><tr><th>ACTION</th><th>KEYBOARD P1</th><th>CONTROLLER</th></tr></thead><tbody><tr><td>Move / aim attack</td><td>W A S D</td><td>Left stick</td></tr><tr><td>Jump / air jump</td><td>Space</td><td>X / Y</td></tr><tr><td>Normal attack</td><td>J + direction</td><td>A + direction</td></tr><tr><td>Smash attack</td><td>Shift + direction + J</td><td>Right stick</td></tr><tr><td>Switch stance</td><td>I</td><td>LB</td></tr><tr><td>Glide</td><td>Hold Space after final air jump</td><td>Hold X / Y</td></tr><tr><td>Drop through platform</td><td>S</td><td>Stick down</td></tr><tr><td>Pause / frame tools</td><td>Esc / Tab</td><td>Keyboard</td></tr></tbody></table><p>P2: arrow keys, Numpad 0 to jump, Numpad 1 to attack, Numpad 5 to switch. A second controller also works.</p><p class="note">This is the foundation and feel build: Mirror Sanctum, movement, stances, and normal attacks. Defense, specials, Fracture rounds, Oaths, and online play are not implemented here. Blast-zone falls reset for practice.</p><button class="primary" id="close-help-bottom">RETURN <span>↗</span></button></section></div>`;}
function renderUi(){
 if(menu){app.innerHTML=`<header class="topline"><div class="brand"><span class="sigil">♜</span> SOULFIRE LEGENDS</div><span class="build">PLAYABLE DEVELOPMENT BUILD · FEEL GATE</span></header><div class="corner-line"></div><main class="hero"><div class="eyebrow">A duel with your reflection</div><h1>SPECTRIS<span>DUELLUM</span></h1><div class="divider"></div><p class="tagline">Face the knight who knows<br>every move you know.</p><nav class="menu"><button class="primary" id="practice">ENTER THE SANCTUM <span>↗</span></button><button class="menu-secondary" id="local">Local sparring <span>02 PLAYERS</span></button><button class="menu-secondary" id="controls">Learn the blade <span>CONTROLS</span></button></nav></main><div class="knight-label">An empty helm. An unbroken will.<small>THE UNSWORN KNIGHT</small></div><footer class="title-bottom"><div class="caption">ONE KNIGHT. TWO STANCES.<br><span class="title-mark">EVERY DECISION LEAVES A CRACK.</span></div><div id="connection">KEYBOARD + CONTROLLER</div><div>SLU / 001</div></footer>${showHelp?controls():''}`;
  on('#practice',()=>start());on('#local',()=>start(true));on('#controls',()=>{showHelp=true;renderUi();});
 }else{
 app.innerHTML=`<div class="hud">${hud(0)}<div class="hud-center">TRUE MIRROR<b>THE SANCTUM</b><small>${local?'LOCAL SPARRING':'MOVEMENT & NORMALS'} · FEEL BUILD</small></div>${hud(1)}</div><div class="announcement" id="intro">IGNITE<small>MEET YOUR REFLECTION</small></div><div class="arena-label">Mirror Sanctum<small>NO OATH. NO ADVANTAGE.</small></div><div class="bottom-bar"><div class="key-hints"><span><kbd>WASD</kbd> Move</span><span><kbd>Space</kbd> Jump</span><span><kbd>J</kbd> Strike</span><span><kbd>I</kbd> Stance</span></div><div><button id="tools">${dev?'Hide':'Show'} tools · Tab</button> <button id="help">Controls</button> <button id="pause">${paused?'Resume':'Pause'} · Esc</button></div></div>${dev?devUi():''}${paused&&!showHelp?`<div class="modal-shade"><div class="modal" style="max-width:440px"><div class="eyebrow">A moment of stillness</div><div class="pause-title">The flame waits.</div><p>Your exchange is paused.</p><button class="primary" id="resume">RESUME <span>↗</span></button><button class="menu-secondary" id="restart">Reset the Sanctum</button><button class="menu-secondary" id="save-pause">Save input replay</button><button class="menu-secondary" id="leave">Return to title</button></div></div>`:''}${showHelp?controls():''}<input class="replay-file" id="file" type="file" accept=".json">`;
 on('#tools',()=>{dev=!dev;renderUi();});on('#help',()=>{showHelp=true;paused=true;renderUi();});on('#pause',togglePause);on('#resume',togglePause);on('#restart',()=>start(local));on('#leave',title);on('#save-pause',saveReplay);bindDev();
 }
 on('#close-help',closeHelp);on('#close-help-bottom',closeHelp);
}
function closeHelp(){showHelp=false;if(!menu)paused=false;renderUi();}
function togglePause(){paused=!paused;accumulator=0;shell.input.clear();renderUi();}
function hud(i:number){return `<div class="fighter-hud ${i?'right':''}" style="color:${i?'#e8a975':'#8ce2da'}"><div class="helm-icon"></div><div><h3>${i?'The Reflection':'The Unsworn'}</h3><div class="sub" id="stance-${i}">P${i+1} / WINGS</div><div class="strain" id="strain-${i}">0<small>STRAIN</small></div><div class="air-pips" id="jumps-${i}"></div></div></div>`;}
function devUi(){return `<aside class="dev"><h3>THE FEEL WORKBENCH</h3><label>Reflection<select id="dummy"><option value="still">Stationary</option><option value="mirror">Mirror inputs</option><option value="patrol">Movement drill</option></select></label><label>Hit / hurt volumes<input type="checkbox" id="boxes" ${debug?'checked':''}></label><label>Sound<input type="checkbox" id="sound" ${shell.audio.enabled?'checked':''}></label><button id="reset">Reset</button><button id="freeze">Freeze</button><button id="advance">+1 frame</button><button id="thaw">Run</button><label>P2 Strain<input id="strain-set" type="number" min="0" max="999" value="${world.fighters[1]!.percentTenths/10}"></label><hr><h3>INPUT REPLAY</h3><label>Slot<select id="slot">${slots.map((v,i)=>`<option value="${i}">${i+1} · ${v?'Recorded':'Empty'}</option>`).join('')}</select></label><button id="record">New recording</button><button id="store">Store slot</button><button id="play">Play slot</button><button id="save">Export JSON</button><button id="load">Load JSON</button><hr><h3>MOVE TUNING · SESSION ONLY</h3><label>Move<select id="move-select">${[...MOVES].map(([id,m])=>`<option value="${id}">${id.startsWith('wings')?'W':'C'} · ${m.name}</option>`).join('')}</select></label><label>First startup<input id="startup" type="number" min="1" max="60" value="2"></label><button id="apply-tuning">Apply & restart recording</button><p style="color:#678b91;font-size:9px">Tuning invalidates earlier replay slots. Source defaults reload on refresh.</p><pre id="telemetry"></pre></aside>`;}
let frozen=false;
function bindDev(){if(!dev)return;
 const d=$<HTMLSelectElement>('#dummy');d.value=dummy;d.onchange=()=>{dummy=d.value;};
 $<HTMLInputElement>('#boxes').onchange=e=>debug=(e.target as HTMLInputElement).checked;
 $<HTMLInputElement>('#sound').onchange=e=>shell.audio.enabled=(e.target as HTMLInputElement).checked;
 on('#reset',()=>{world=createSession();previous=world;playback=null;record();});on('#freeze',()=>frozen=true);on('#thaw',()=>frozen=false);on('#advance',()=>{frozen=true;tick();previous=world;});
 $<HTMLInputElement>('#strain-set').onchange=e=>{const value=Number((e.target as HTMLInputElement).value);if(!Number.isFinite(value))return;world=structuredClone(world);world.fighters[1]!.percentTenths=Math.round(Math.max(0,Math.min(999,value))*10);previous=world;record();};
 const sel=$<HTMLSelectElement>('#slot');sel.value=String(slot);sel.onchange=()=>slot=Number(sel.value);
 on('#record',()=>{playback=null;record();toast('Recording from the current state');});on('#store',()=>{slots[slot]=recorder.finish();renderUi();toast(`Stored slot ${slot+1}`);});on('#play',()=>{if(slots[slot])loadReplay(slots[slot]!);else toast('This slot is empty. Store an exchange first.');});on('#save',saveReplay);
 on('#load',()=>$<HTMLInputElement>('#file').click());$<HTMLInputElement>('#file').onchange=async e=>{const file=(e.target as HTMLInputElement).files?.[0];if(file)try{loadReplay(JSON.parse(await file.text()) as ReplayTape);}catch(error){toast(`Replay rejected: ${String(error).slice(0,90)}`);}};
 const moveSel=$<HTMLSelectElement>('#move-select');moveSel.onchange=()=>$<HTMLInputElement>('#startup').value=String(MOVES.get(moveSel.value)!.strikes[0]!.start);
 on('#apply-tuning',()=>{const m=MOVES.get(moveSel.value)!,value=Number($<HTMLInputElement>('#startup').value);if(!Number.isInteger(value)||value<1||value>60)return toast('Startup must be an integer from 1 to 60.');const delta=value-m.strikes[0]!.start;m.strikes=m.strikes.map(s=>({...s,start:s.start+delta}));m.faf+=delta;ATTACKS.clear();for(const [id,a] of compileMoves())ATTACKS.set(id,a);slots=slots.map(()=>null);playback=null;record();toast('Applied. Replay slots cleared for the changed rules.');});
}
function saveReplay(){downloadJson(recorder.finish(),'spectris-exchange.json');toast('Replay exported');}
function loadReplay(value:ReplayTape){if(value.metadata.gameVersion!=='spectris-feel-v1'||value.frames.length>216000)throw new Error('Unsupported replay or too many frames');const player=new ReplayPlayer(value,stepSession);player.playToEnd();tape=value;playback=player;world=player.seek(player.startFrame);previous=world;playbackFrames=new Map(value.frames.map(i=>[i.frame,i]));frozen=false;paused=false;menu=false;renderUi();toast('Playing verified input replay');}
function dummyInput(frame:number,p1:SimInputFrame):SimInputFrame{if(dummy==='mirror')return {...p1,moveX:-p1.moveX};if(dummy==='patrol')return {...neutral(frame),moveX:frame%180<80?-650:frame%180<160?650:0,jumpPressed:frame%100===0,jumpHeld:frame%100<30,attackPressed:frame%40===0,auxiliaryButtons:frame%240===0?1:0};return neutral(frame);}
function tick(){previous=world;const begin=performance.now();let result;
 if(playback){const input=playbackFrames.get(world.frame);if(!input){playback=null;frozen=true;toast('Replay complete');return;}result=stepSession(world,input);}
 else{lastInput=shell.input.sample(0,world.frame);const input={frame:world.frame,byFighterId:{'player-1':lastInput,'player-2':local?shell.input.sample(1,world.frame):dummyInput(world.frame,lastInput)}};result=stepSession(world,input);recorder.append(input,result.state);}
 world=result.state;simMs=performance.now()-begin;steps++;
 for(const event of result.events){if(event.type==='hit'){const p=world.fighters.find(p=>p.id===event.targetId)!;renderer.hit(f.toNumber(p.x),f.toNumber(p.y)+1.5);shell.audio.cue('hit');}else if(event.type==='clank')shell.audio.cue('clank');}
 for(const p of world.fighters){const before=previous.fighters.find(v=>v.id===p.id)!;if(p.definitionId!==before.definitionId)shell.audio.cue('stance');if(p.vy>before.vy&&p.hitstunFrames===0)shell.audio.cue('jump');}
}
function updateHud(now:number){if(menu){const el=app.querySelector('#connection');if(el)el.textContent=shell.input.connected?`${shell.input.connected} CONTROLLER${shell.input.connected>1?'S':''} CONNECTED`:'KEYBOARD + CONTROLLER';return;}
 const d=gameData(world);world.fighters.forEach((p,i)=>{const k=d.knights[p.id]!;const s=app.querySelector(`#stance-${i}`);if(s)s.textContent=`P${i+1} / ${k.stance.id.toUpperCase()}${k.gliding?' · GLIDE':k.stance.unfurl?' · UNFURL':''}`;const n=app.querySelector(`#strain-${i}`);if(n)n.innerHTML=`${Math.floor(p.percentTenths/10)}<small>STRAIN</small>`;const j=app.querySelector(`#jumps-${i}`);if(j)j.innerHTML=Array.from({length:k.stance.id==='wings'?3:2},(_,i)=>`<i class="${i>=p.jumpsRemaining?'empty':''}"></i>`).join('');});
 const intro=app.querySelector<HTMLElement>('#intro');if(intro)intro.style.opacity=now<introUntil?'1':'0';
 const telemetry=app.querySelector('#telemetry');if(telemetry&&steps%6===0){const p=world.fighters[0]!,move=p.attack?MOVES.get(p.attack.attackId):null;telemetry.textContent=`${frozen?'FROZEN':playback?'REPLAY':'LIVE'} · ${world.frame}f · ${fps.toFixed(0)} fps\nSim ${simMs.toFixed(2)}ms · ${hashWorldState(world)}\n${move?.name??p.locomotion} ${p.attack?.frame??''}\nInput ${lastInput.moveX}, ${lastInput.moveY}\n${gameData(world).knights[p.id]!.stance.switchedAirborne?'Air switch spent':'Air switch available'}`;}
}
addEventListener('keydown',e=>{if((e.target as HTMLElement)?.matches('input,select,textarea')||e.repeat)return;if(e.code==='Escape'){if(showHelp)closeHelp();else if(!menu)togglePause();}if(e.code==='Tab'&&!menu){dev=!dev;renderUi();}if(e.code==='Period'&&!menu){frozen=true;tick();}if(e.code==='Enter'&&menu&&!showHelp)start();});
addEventListener('blur',()=>{if(!menu&&!paused){paused=true;renderUi();}});
function frame(now:number){const rawElapsed=now-lastTime,elapsed=Math.min(100,rawElapsed);lastTime=now;frameTimes.push(rawElapsed);if(frameTimes.length>60)frameTimes.shift();fps=1000/(frameTimes.reduce((a,b)=>a+b,0)/frameTimes.length);
 if(!menu&&!paused&&!frozen)accumulator+=elapsed;else accumulator=0;
 let n=0;while(accumulator>=1000/60&&n<6){tick();accumulator-=1000/60;n++;}
 renderer.render(world,paused||frozen?1:accumulator/(1000/60),previous,now,menu,debug);updateHud(now);if(now>toastUntil)app.querySelector('.toast')?.remove();requestAnimationFrame(frame);
}
const hooks={getState:()=>structuredClone(world),setState:(state:WorldState)=>{gameData(state);world=structuredClone(state);previous=world;record();},step:(frames=1)=>{for(let i=0;i<Math.min(10000,frames);i++)tick();return structuredClone(world);},hash:()=>hashWorldState(world),start,loadReplay,pause:()=>{frozen=true;},resume:()=>{frozen=false;},input:(input:SimInputFrame)=>{const result=stepSession(world,{frame:world.frame,byFighterId:{'player-1':{...input,frame:world.frame},'player-2':neutral(world.frame)}});world=result.state;previous=world;return world;},metrics:()=>({fps,simMs,drawCalls:renderer.renderer.info.render.calls,triangles:renderer.renderer.info.render.triangles}),saveReplay:()=>recorder.finish()};
Object.assign(window,{__spectris:hooks});renderUi();requestAnimationFrame(frame);
